name: my-propagators
version: 0.1.0

ghc-options: -fprint-potential-instances -Wall -Werror -Wno-unused-do-bind

executable:
  source-dirs: src
  main: Main.hs

dependencies:
  # essentially standard library
  - base
  - text
  - containers
  - transformers
  - mtl
  - bytestring
  - time
  # macros
  - template-haskell
  # parser combinators
  - parsec
  # others
  - primitive
  - hashable
  - unordered-containers
  - vector
  - constraints

# enable modern Haskell
default-extensions:
  # quality of live
  - PackageImports
  - ImportQualifiedPost
  - LambdaCase
  - OverloadedStrings
  - OverloadedLists
  - TypeApplications
  - TupleSections
  - PatternSynonyms
  - ViewPatterns
  - InstanceSigs

  # deriving
  - StandaloneDeriving
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - EmptyDataDeriving
  - DerivingVia
  - DeriveGeneric
  - DeriveFunctor
  - DeriveTraversable
  - DeriveFoldable
  - DeriveDataTypeable
  - DeriveLift

  # typesysteme
  - QuantifiedConstraints
  - PolyKinds
  - ExistentialQuantification
  - GADTs
  - DataKinds
  - RankNTypes
  - MultiParamTypeClasses
  - FunctionalDependencies
  - ConstraintKinds
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - ScopedTypeVariables
  - FlexibleInstances
  - FlexibleContexts
  - UndecidableInstances
